## Expected Behavior


## Actual Behavior


## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - pygce version (check `pip3 show pygce`):
  - Platform (e.g `Windows 8`, `Mac OSX Sierra`, `Ubuntu 18.04` ...):
  - Url of connection (e.g `https://connect.garmin.com`, if you don't know it,
  then it's the stock one: `https://connect.garmin.com`):
  - Python version (check `python --version`):
